import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { extractCharsFromSource, extractStrokePaths } from './kanjivg-parser.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const CONCURRENCY = 8;

function readChars(relativePath, fieldName) {
  const source = readFileSync(path.join(root, relativePath), 'utf-8');
  return extractCharsFromSource(source, fieldName);
}

async function fetchStrokesForChar(char) {
  const hex = char.codePointAt(0).toString(16).padStart(5, '0');
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${hex}.svg`;
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const svg = await res.text();
    const strokes = extractStrokePaths(svg);
    return strokes.length > 0 ? strokes : null;
  } catch {
    return null;
  }
}

async function run() {
  const hiraganaChars = readChars('src/data/hiragana.ts', 'char');
  const katakanaChars = readChars('src/data/katakana.ts', 'char');
  const kanjiChars = readChars('src/data/kanji.ts', 'kanji');
  const chars = [...new Set([...hiraganaChars, ...katakanaChars, ...kanjiChars])];

  const strokeData = {};
  const skipped = [];

  for (let i = 0; i < chars.length; i += CONCURRENCY) {
    const batch = chars.slice(i, i + CONCURRENCY);
    const results = await Promise.all(batch.map(async char => [char, await fetchStrokesForChar(char)]));
    for (const [char, strokes] of results) {
      if (strokes) strokeData[char] = strokes;
      else skipped.push(char);
    }
    console.log(`Fetched ${Math.min(i + CONCURRENCY, chars.length)}/${chars.length}`);
  }

  const output = `// Generated by scripts/fetch-kanjivg.mjs — do not edit by hand.
// Stroke data (c) KanjiVG project (https://kanjivg.tagaini.net), CC BY-SA 3.0.

export const STROKE_VIEWBOX = '0 0 109 109';

export const strokeData: Record<string, string[]> = ${JSON.stringify(strokeData, null, 2)};
`;

  writeFileSync(path.join(root, 'src/data/strokes.ts'), output);
  console.log(`Wrote strokes for ${Object.keys(strokeData).length}/${chars.length} characters.`);
  if (skipped.length > 0) {
    console.log(`Skipped (no KanjiVG data found): ${skipped.join(' ')}`);
  }
}

run();
